apiVersion: v1
kind: Template
metadata:
  name: genexus
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata: 
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  data:
    dataSource.url: "jdbc:oracle:thin:${USER}/${PASSWORD}@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=10.1.10.212)(PORT=1525)))(CONNECT_DATA=(SID=sisaqa)))"
    dataSourceReadOnly.url: "jdbc:oracle:thin:${USER}/${PASSWORD}@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=10.1.10.212)(PORT=1525)))(CONNECT_DATA=(SID=sisaqa)))"
    dataSourceStandByReportes.url: "jdbc:oracle:thin:${USER}/${PASSWORD}@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=10.1.10.212)(PORT=1525)))(CONNECT_DATA=(SID=sisaqa)))"
    dataSourceExportImport.url: "jdbc:oracle:thin:${USER}/${PASSWORD}@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=10.1.10.212)(PORT=1525)))(CONNECT_DATA=(SID=sisaqa)))"
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: genexus